### ISSUE TITLE
[Proposal] Move zombie entities to NPCs/zombies.

### ISSUE THREAD

**Issue by malortie** [SamVanheer/halflife-unified-sdk#222]
I believe zombies are technically not aliens.

I propose to move them to NPCs/zombies:

```
NPCs/zombies/
  gonome.cpp
  zombie.cpp
  zombie.h
  zombie_barney.cpp
  zombie_soldier.cpp
```

**Comment by SamVanheer** [comment]
I concur, i'll move it to the proposed location.

**Comment by SamVanheer** [comment]
I'll move the remaining files once all changes from updated-cmake have been merged in.
