### ISSUE TITLE
Customizable Hud Color?

### ISSUE THREAD

**Issue by OpenRift412** [SamVanheer/halflife-unified-sdk#237]
Being able to [change the HUD color](https://twhl.info/wiki/page/VERC%3A_Customizable_Hud_Color) would be great for when you want the additional cosmetic fixes in the mod you're playing without it affecting the intended HUD color. Just making sure, is that possible?

**Comment by SamVanheer** [comment]
I've added support for this. There is an entity `player_sethudcolor` that can set and reset the color, and a cheat command `set_hud_color` can do the same thing.

Usage: `set_hud_color <r> <g> <b>` (values in range 0-255)

The color is saved so if you set it at the start of a campaign playthrough it'll stick, but it will not carry over to other sessions that don't have the same save game state.

There is no game installation to test this with yet so you'll have to wait to try it. You can try using the compiled dlls from the [Github Actions](https://github.com/SamVanheer/halflife-unified-sdk/actions) page but without the rest of the game installation it might not work so well. Note that these are development builds and may be buggy or slow.
