### ISSUE TITLE
[Enhancement] Implement compound assignment operators for Vector.

### ISSUE THREAD

**Issue by malortie** [SamVanheer/halflife-unified-sdk#292]
As an example, there are several places in client code where each Vector component is updated within a loop.

https://github.com/SamVanheer/halflife-unified-sdk/blob/ad4c370a81e133f3641ac030f767b2f76db22369/src/game/client/view.cpp#L631-L634

I would propose to implement and use operators (+= -= *= /=) where applicable to simplify code.

**Comment by SamVanheer** [comment]
As i said in #291, we should probably switch to GLM since it already implements operations like this.

**Comment by malortie** [comment]
Closed in favor of #291 .
