### ISSUE TITLE
Implement secondary SF for item_generic from CZDS to make model a SOLID_SLIDEBOX / size based on mins & maxs

### ISSUE THREAD

**Issue by SmileyAG** [SamVanheer/halflife-unified-sdk#300]
In `CGenericItem::Spawn` (**cz.so**):

![sf](https://user-images.githubusercontent.com/58108407/162015855-9c187a5f-26bc-48b7-b5db-0577f3ddc73c.PNG)

There is no specified all variables at end of `at_console`, but I found similar message at `CGenericItem::StartItem`:

![startitem](https://user-images.githubusercontent.com/58108407/162017424-6eb9048f-29ce-4f36-b168-d041eb269461.PNG)

**Comment by SamVanheer** [comment]
Disassemblers tend to have trouble figuring out varargs functions like AlertMessage. You should be able to right click the call and use `Add variadic argument` to make it add whatever's next on the stack as an argument. This only works correctly if the code actually passed enough arguments though.

I'll implement the feature later, once i've wrapped up other work.
