### ISSUE TITLE
EAX/A3D Emulation

### ISSUE THREAD

**Issue by OpenRift412** [SamVanheer/halflife-unified-sdk#348]
So I noticed some code mentioning implementation of OpenAL into the SDK, are there plans to emulate EAX and/or A3D effects found in the WON version of the game?

**Comment by SamVanheer** [comment]
The new sound system uses EAX and has support for enabling HRTF, which is OpenAL's approach to A3D.

Note that this is a different technology doing the same kind of thing so it won't sound exactly the same.
