### ISSUE TITLE
Shock Roach texture issue

### ISSUE THREAD

**Issue by Ronin4862** [SamVanheer/halflife-unified-sdk#426]
I'm having this corrupt textures issue with the Shock Roach. It seems to appear only in some instances, but not always.

It's not my OpenGL drivers as I have done a clean install of the latest Geforce Drivers and also did a Restore in Nvidia Control Panel.

https://youtu.be/OvBTUEUj2Zk

**Comment by SamVanheer** [comment]
This bug has been fixed. The latest pre-alpha build includes a modified model that does not have the polygons in question.
