### ISSUE TITLE
Wrong scientist model used in Blue Shift training.

### ISSUE THREAD

**Issue by malortie** [SamVanheer/halflife-unified-sdk#438]
In the original Blue Shift, the duck jump room features Rosenberg as the scientist observing the test. This happens because Blue Shift doesn't use a separate model and uses the 4th slot of scientist heads submodel.

In the Unified SDK, Rosenberg was moved to a separate model so it does not override the default slick model.

Current Blue Shift Steam release:

![image](https://user-images.githubusercontent.com/12233175/210461183-70d7739f-86b4-435f-9a1e-30871747c1d3.png)

Unified SDK:

![image](https://user-images.githubusercontent.com/12233175/210461215-74f66393-4da2-4daa-b2ff-2f7c35c36e50.png)

**Solution**

The [MapUpgrader](https://github.com/SamVanheer/HalfLife.UnifiedSdk-CSharp/tree/master/src/HalfLife.UnifiedSdk.MapUpgrader.Upgrades/BlueShift) might require a new case to use Rosenberg in `ba_hazard1.bsp`:

```
{
"origin" "1592 840 28"

"body" "3" <--- Remove

"spawnflags" "258"
"angle" "275"

"classname" "monster_scientist" <--- Replace with "monster_rosenberg"
}
```

**In-game version**

```
Build type: Release
Release type: Pre-Alpha
Client:
  Version 1.0.0
  Branch: master
  Tag: CI build
  Commit Hash: f47c2f6a405aa33b386b63188067e1853484687e
Server:
  Version 1.0.0
  Branch: master
  Tag: CI build
  Commit Hash: f47c2f6a405aa33b386b63188067e1853484687e

WIP build not suited for use (testing only)
```

**Comment by SamVanheer** [comment]
Fixed by SamVanheer/HalfLife.UnifiedSdk-CSharp#4.
