### ISSUE TITLE
Grunts AI sentences refer to Freeman in Blue Shift maps.

### ISSUE THREAD

**Issue by malortie** [SamVanheer/halflife-unified-sdk#439]
In Half-Life 1, the following sentences contain the word 'freeman' and were changed in Blue Shift to 'hostiles'.

- HG_ALERT0
- HG_ALERT4
- HG_ALERT5
- HG_QUEST11

The sentences are already defined in Unified SDK sentences.txt and would just need to be used.

https://github.com/SamVanheer/halflife-unified-sdk-assets/blob/85655e547f0a2331f0d06e53b3b6842b439d604b/soundsrc/sentences.txt#L35-L40

https://github.com/SamVanheer/halflife-unified-sdk-assets/blob/85655e547f0a2331f0d06e53b3b6842b439d604b/soundsrc/sentences.txt#L136

**In-game version**

```
Build type: Release
Release type: Pre-Alpha
Client:
  Version 1.0.0
  Branch: master
  Tag: CI build
  Commit Hash: f47c2f6a405aa33b386b63188067e1853484687e
Server:
  Version 1.0.0
  Branch: master
  Tag: CI build
  Commit Hash: f47c2f6a405aa33b386b63188067e1853484687e

WIP build not suited for use (testing only)
```

**Comment by malortie** [comment]
The original test was made on `ba_power1`.

After inspecting configuration files, the mapping to use Blue Shift grunt sentences exists:

https://github.com/SamVanheer/halflife-unified-sdk-assets/blob/85655e547f0a2331f0d06e53b3b6842b439d604b/cfgsrc/BlueShiftSentenceReplacement.json#L3-L4

The issue likely occurs because several scripted sentences play the HL1 variants.  They will likely need to be changed to play the Blue Shift variants.

```
"sentence" "!HG_ALERT2" <----- Change to BSHG_ALERT2
"sentence" "!HG_TAUNT1"
"sentence" "!HG_ALERT0" <----- Change to BSHG_ALERT0
"sentence" "!HG_COVER5"
"sentence" "!HG_COVER1"
```

**Comment by SamVanheer** [comment]
Fixed by SamVanheer/HalfLife.UnifiedSdk-CSharp#5.
