### ISSUE TITLE
Wrong scientist head used in ba_yard1.

### ISSUE THREAD

**Issue by malortie** [SamVanheer/halflife-unified-sdk#441]
In the original Blue Shift `ba_yard1`, one of the `monster_scientist_dead` entities uses the fourth scientist head (Rosenberg), although this is not noticeable because the tunnel door closes before the player can reach the parking area.

```
{
"origin" "427 338 0"
"body" "3"
"rendercolor" "0 0 0"
"renderamt" "0"
"rendermode" "0"
"renderfx" "0"
"pose" "0"
"angle" "315"
"classname" "monster_scientist_dead"
}
```

in `ba_yard4`, the same dead scientist head value is set to first head (Glasses).

```
{
"origin" "427 -2062 0"
"body" "0"
"rendercolor" "0 0 0"
"renderamt" "0"
"rendermode" "0"
"renderfx" "0"
"pose" "0"
"angle" "315"
"classname" "monster_scientist_dead"
}
```

**Comment by SamVanheer** [comment]
Fixed by SamVanheer/HalfLife.UnifiedSdk-CSharp#4.
