### ISSUE TITLE
Opposing Force uses HL1 HUD digits.

### ISSUE THREAD

**Issue by malortie** [SamVanheer/halflife-unified-sdk#506]
**Description**

When playing through any map of the Opposing Force campaign, the HUD digits use the ones from HL1 HEV. The vertical divider between health and suit icons appears to use non-scanline version.

**Steps to reproduce**

1. Open the console and type the following:

   ```
   sv_cheats 1
   map ofboot1
   give item_suit
   ```

**Build** : [Half-Life Unified SDK V1.0.0 Release Candidate 001](https://github.com/SamVanheer/halflife-unified-sdk/releases/tag/UNIFIED-V1.0.0-RC001)

**Project info**

Using `cl_projectinfo_print_all` :

```
Project info for client:
Version: 1.0.0-Beta
Branch: master
Tag: UNIFIED-V1.0.0-RC001
Commit Hash: 68ea0b7ec048935f1e1e740c5778aedebb00458d
Build Timestamp: 20:02:58 Jul 30 2023
Project info for server:
Version: 1.0.0-Beta
Branch: master
Tag: UNIFIED-V1.0.0-RC001
Commit Hash: 68ea0b7ec048935f1e1e740c5778aedebb00458d
Build Timestamp: 20:03:54 Jul 30 2023
```

**Comment by SamVanheer** [comment]
I checked this and the digits are all using scanline versions. The separator is correct, it matches Opposing Force's original divider.

Can you make a screenshot showing the incorrect digits?

**Comment by malortie** [comment]
Unified SDK:

<img width="800" alt="ofboot1_hud_opfor_hlu" src="https://github.com/SamVanheer/halflife-unified-sdk/assets/12233175/c5f737f3-a31e-4b82-9b42-647e9228c655">

Original Op4:

<img width="800" alt="ofboot1_hud_opfor_op4" src="https://github.com/SamVanheer/halflife-unified-sdk/assets/12233175/3c672647-a2ba-4ea7-a9ff-177e5fe3b294">

**Comment by SamVanheer** [comment]
Ok i see it now. It's using the wrong sprite for the numbers.
