### ISSUE TITLE
Osprey on_tarmac sequence not restored after reloading the game.

### ISSUE THREAD

**Issue by malortie** [SamVanheer/halflife-unified-sdk#508]
**Description**

In map `ofboot1`, an Osprey can be seen playing sequence `on_tarmac` behind the fence.

When saving and reloading the game, the Osprey goes back to sequence 0 `rotor`.

This issue does not occur in the original game.

**Steps to reproduce**

1. Open the console and type the following:
    ```
    sv_cheats 1
    map ofboot1
    ```
3. Move to the Osprey area
4. Save the game
5. Reload the game

**Build** : [Half-Life Unified SDK V1.0.0 Release Candidate 001](https://github.com/SamVanheer/halflife-unified-sdk/releases/tag/UNIFIED-V1.0.0-RC001)

**Project info**

Using `cl_projectinfo_print_all` :

```
Project info for client:
Version: 1.0.0-Beta
Branch: master
Tag: UNIFIED-V1.0.0-RC001
Commit Hash: 68ea0b7ec048935f1e1e740c5778aedebb00458d
Build Timestamp: 20:02:58 Jul 30 2023
Project info for server:
Version: 1.0.0-Beta
Branch: master
Tag: UNIFIED-V1.0.0-RC001
Commit Hash: 68ea0b7ec048935f1e1e740c5778aedebb00458d
Build Timestamp: 20:03:54 Jul 30 2023
```

**Comment by SamVanheer** [comment]
This does happen in the original game, it's just that in addition to the animation resetting the Unified SDK version of the model has the ground at the height of the wings instead of at the height of the bottom of the wheels.
