### ISSUE TITLE
(of2a5) Engineer ally grunt does not deploy his gun.

### ISSUE THREAD

**Issue by malortie** [SamVanheer/halflife-unified-sdk#510]
**Description**

See https://github.com/ValveSoftware/halflife/issues/3362

This will likely require to reuse an animation that draws and enables the gun using animation events, or edit the existing one.

**Note:** A separate animation could be created to allow mappers to choose between standing up deploying the torch or the gun.

**Build** : [Half-Life Unified SDK V1.0.0 Release Candidate 001](https://github.com/SamVanheer/halflife-unified-sdk/releases/tag/UNIFIED-V1.0.0-RC001)

**Project info**

Using `cl_projectinfo_print_all` :

```
Project info for client:
Version: 1.0.0-Beta
Branch: master
Tag: UNIFIED-V1.0.0-RC001
Commit Hash: 68ea0b7ec048935f1e1e740c5778aedebb00458d
Build Timestamp: 20:02:58 Jul 30 2023
Project info for server:
Version: 1.0.0-Beta
Branch: master
Tag: UNIFIED-V1.0.0-RC001
Commit Hash: 68ea0b7ec048935f1e1e740c5778aedebb00458d
Build Timestamp: 20:03:54 Jul 30 2023
```

**Comment by SamVanheer** [comment]
This is intentional. The grunt is supposed to be killed by the sentry. This map and `ofboot4` are the only ones to use this particular animation while the other 2 cases use the alternate animation that does equip the gun.
