### ISSUE TITLE
(of2a5) Engineer ally grunt invincible to propane explosion while in scripted sequence.

### ISSUE THREAD

**Issue by malortie** [SamVanheer/halflife-unified-sdk#511]
**Description**

See https://github.com/ValveSoftware/halflife/issues/3363

**Build** : [Half-Life Unified SDK V1.0.0 Release Candidate 001](https://github.com/SamVanheer/halflife-unified-sdk/releases/tag/UNIFIED-V1.0.0-RC001)

**Project info**

Using `cl_projectinfo_print_all` :

```
Project info for client:
Version: 1.0.0-Beta
Branch: master
Tag: UNIFIED-V1.0.0-RC001
Commit Hash: 68ea0b7ec048935f1e1e740c5778aedebb00458d
Build Timestamp: 20:02:58 Jul 30 2023
Project info for server:
Version: 1.0.0-Beta
Branch: master
Tag: UNIFIED-V1.0.0-RC001
Commit Hash: 68ea0b7ec048935f1e1e740c5778aedebb00458d
Build Timestamp: 20:03:54 Jul 30 2023
```

**Comment by SamVanheer** [comment]
This is the case for NPCs in general. They won't die until they exit the scripted sequence unless the script is somehow interrupted.
