### ISSUE TITLE
Gordon head mesh visible through dead HEV scientists helmets.

### ISSUE THREAD

**Issue by malortie** [SamVanheer/halflife-unified-sdk#512]
**Description**

See https://github.com/ValveSoftware/halflife/issues/3364

**Build** : [Half-Life Unified SDK V1.0.0 Release Candidate 001](https://github.com/SamVanheer/halflife-unified-sdk/releases/tag/UNIFIED-V1.0.0-RC001)

**Project info**

Using `cl_projectinfo_print_all` :

```
Project info for client:
Version: 1.0.0-Beta
Branch: master
Tag: UNIFIED-V1.0.0-RC001
Commit Hash: 68ea0b7ec048935f1e1e740c5778aedebb00458d
Build Timestamp: 20:02:58 Jul 30 2023
Project info for server:
Version: 1.0.0-Beta
Branch: master
Tag: UNIFIED-V1.0.0-RC001
Commit Hash: 68ea0b7ec048935f1e1e740c5778aedebb00458d
Build Timestamp: 20:03:54 Jul 30 2023
```

**Comment by SamVanheer** [comment]
This is a problem with the model, i suppose Gordon's head should be moved to the `player_template_biped(Gordon_Head)1` body group to fix this.

**Comment by malortie** [comment]
Fixed in https://github.com/SamVanheer/halflife-unified-sdk-assets/pull/135.
