### ISSUE TITLE
Players can push drill sergeants away as with followers.

### ISSUE THREAD

**Issue by malortie** [SamVanheer/halflife-unified-sdk#517]
**Description**

See https://github.com/ValveSoftware/halflife/issues/3369

**Note:** Additional actions are required to trigger the issue in the unified SDK.

**Steps to reproduce**

1. Follow all steps in the original bug report.
2. Open the console and type the following:
   ```
   host_framerate 0.09
   ```
3. Press +USE repeatedly while pushing against the sergeant.

Sergeant eventually moves away.

In some cases, when pushing, it's easier to trigger the issue while standing instead of crouching.

**Build** : [Half-Life Unified SDK V1.0.0 Release Candidate 001](https://github.com/SamVanheer/halflife-unified-sdk/releases/tag/UNIFIED-V1.0.0-RC001)

**Project info**

Using `cl_projectinfo_print_all` :

```
Project info for client:
Version: 1.0.0-Beta
Branch: master
Tag: UNIFIED-V1.0.0-RC001
Commit Hash: 68ea0b7ec048935f1e1e740c5778aedebb00458d
Build Timestamp: 20:02:58 Jul 30 2023
Project info for server:
Version: 1.0.0-Beta
Branch: master
Tag: UNIFIED-V1.0.0-RC001
Commit Hash: 68ea0b7ec048935f1e1e740c5778aedebb00458d
Build Timestamp: 20:03:54 Jul 30 2023
```

**Comment by SamVanheer** [comment]
This is because drill sergeants inherit from `CTalkMonster` which has logic to have NPCs walk away if the player runs into them. Since drill sergeants only show up in the boot camp levels and this doesn't cause any problems it's not worth fixing.
