### ISSUE TITLE
(t0a0d, ba_hazard6) Elevator doors don't open when loading map from the console.

### ISSUE THREAD

**Issue by malortie** [SamVanheer/halflife-unified-sdk#518]
**Description**

See https://github.com/ValveSoftware/halflife/issues/3371

If possible, find a way to trigger `elestartmm` when loading `t0a0d` without interfering with the existing logic from `t0a0c` to `t0a0d`.

**Build** : [Half-Life Unified SDK V1.0.0 Release Candidate 001](https://github.com/SamVanheer/halflife-unified-sdk/releases/tag/UNIFIED-V1.0.0-RC001)

**Project info**

Using `cl_projectinfo_print_all` :

```
Project info for client:
Version: 1.0.0-Beta
Branch: master
Tag: UNIFIED-V1.0.0-RC001
Commit Hash: 68ea0b7ec048935f1e1e740c5778aedebb00458d
Build Timestamp: 20:02:58 Jul 30 2023
Project info for server:
Version: 1.0.0-Beta
Branch: master
Tag: UNIFIED-V1.0.0-RC001
Commit Hash: 68ea0b7ec048935f1e1e740c5778aedebb00458d
Build Timestamp: 20:03:54 Jul 30 2023
```

**Comment by SamVanheer** [comment]
You can open the elevator doors by +USEing the button outside the elevator through the wall. Since players don't normally load into this level directly there is no need to set up a script to do this (which probably can't be done anyway).
