### ISSUE TITLE
(of3a4, of5a2, of6a4, of6a4b) Xen bullsquids don't attack players.

### ISSUE THREAD

**Issue by malortie** [SamVanheer/halflife-unified-sdk#521]
**Description**

See https://github.com/ValveSoftware/halflife/issues/3375

**Build** : [Half-Life Unified SDK V1.0.0 Release Candidate 001](https://github.com/SamVanheer/halflife-unified-sdk/releases/tag/UNIFIED-V1.0.0-RC001)

**Project info**

Using `cl_projectinfo_print_all` :

```
Project info for client:
Version: 1.0.0-Beta
Branch: master
Tag: UNIFIED-V1.0.0-RC001
Commit Hash: 68ea0b7ec048935f1e1e740c5778aedebb00458d
Build Timestamp: 20:02:58 Jul 30 2023
Project info for server:
Version: 1.0.0-Beta
Branch: master
Tag: UNIFIED-V1.0.0-RC001
Commit Hash: 68ea0b7ec048935f1e1e740c5778aedebb00458d
Build Timestamp: 20:03:54 Jul 30 2023
```

**Comment by SamVanheer** [comment]
These bullsquids are locked in scripted sequences that will never end. Shooting them breaks them out of the animation but they're still being controlled by the script so they won't attack or move.

Since they're supposed to ignore the player don't think it's worth trying to fix this.
