### ISSUE TITLE
(ofboot4) Bootcamp turrets stop firing immediately when player is occluded.

### ISSUE THREAD

**Issue by malortie** [SamVanheer/halflife-unified-sdk#522]
**Description**

In the original Opposing Force, on map `ofboot4`, turrets keep firing for a certain amount of time when the player is occluded behind a hill or behind bags of sand. In the unified SDK, they stop immediately.

You can test with `host_framerate 0.09` in the original game to attest that turrets cease firing after a certain amount of time.

EDIT: The original Op4 turrets also stop firing after a certain amount of time when the player is not occluded, but stands outside of their cone range.

**Steps to reproduce**

1. Open the console and type the following:
   ```
   sv_cheats 1
   map ofboot4
   god
   ```
2. Hide behind a hill. Compare with the original game.
3. Hide behind a bag of sand. Compare with the original game.

**Build** : [Half-Life Unified SDK V1.0.0 Release Candidate 001](https://github.com/SamVanheer/halflife-unified-sdk/releases/tag/UNIFIED-V1.0.0-RC001)

**Project info**

Using `cl_projectinfo_print_all` :

```
Project info for client:
Version: 1.0.0-Beta
Branch: master
Tag: UNIFIED-V1.0.0-RC001
Commit Hash: 68ea0b7ec048935f1e1e740c5778aedebb00458d
Build Timestamp: 20:02:58 Jul 30 2023
Project info for server:
Version: 1.0.0-Beta
Branch: master
Tag: UNIFIED-V1.0.0-RC001
Commit Hash: 68ea0b7ec048935f1e1e740c5778aedebb00458d
Build Timestamp: 20:03:54 Jul 30 2023
```

**Comment by SamVanheer** [comment]
Func_tank entities had some fixes applied a few days ago:
https://github.com/SamVanheer/halflife-unified-sdk/commit/2fb6ed45bbe24d12834f7dcb3f507551efb03cea
https://github.com/SamVanheer/halflife-unified-sdk/commit/f0992b679f4fe30f975bc2b6a964f36377ddfbfe

I tested this map and it works like it does in the original map so i think it's fine now.
